config/routes.rb
Rails.application.routes.draw do
  get 'pre_launch', to: 'pre_launch#index'
  post 'pre_launch/subscribe', to: 'pre_launch#subscribe'
  root to: "pre_launch#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save  :user_not_exists?, :email_downcase! 
  after_create :user_not_exists?, :subscribe_to_mailing_list 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  #validates_format_of :email,with: VALID_EMAIL_REGEX, message: "Niepoprawny email!" 
  #validates_presence_of :email, message: "Proszę podaj swój email."
  #validates_uniqueness_of :email, message: "Ten email już istnieje!"
  validates :email, format:   {with: VALID_EMAIL_REGEX, message: "Upewnij się, czy podany email jest prawidłowy."}
               #     uniqueness: {case_sensitive: false, message: "Mamy już Twój email."}

  private
  def subscribe_to_mailing_list testing=false
    return true if(Rails.env.test? && !testing) 
    list_id = ENV['MAILCHIMP_LIST_ID']

    begin
      response = Rails.configuration.mailchimp.lists.subscribe({
        id: list_id,
        email: {email: email},
        double_optin: false
      })
      rescue Gibbon::MailChimpError => e
        logger.tagged( "MAILCHIMP" ){ logger.error { "Error while subscribing user to Mailchimp: messge: #{e.message}, code #{e.code}"} }
      end
    logger.tagged("MAILCHIMP"){logger.info{ "User subscribed to list #{email}"}}
    response
  end

  def user_not_exists?
    !User.exists?(email: email.downcase)
  end

  def email_downcase!
    email.downcase!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pre_launch_controller.rb
class PreLaunchController < ApplicationController
  layout  "pre_launch"
  def index
    @user = User.new
  end
  def subscribe
      user = User.create(subscription_params)
      if user.valid?
        #TODO stringi do słowników - ror guides I18n
        flash.now[:success] = 'Dziękujemy :)<br/>Niedługo poznasz więcej szczegółów!'.html_safe
        logger.tagged('PRE_LAUNCH'){logger.info { "New user #{user.email}"}}
      else
        #TODO słowniki
        flash.now[:errors] = user.errors
        logger.tagged('PRE_LAUNCH'){logger.warn { "Invalid user #{user.email}"}}
        render action: 'index'
      end 
  end   

  private

  def subscription_params
    params.permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pre_launch_helper.rb
module PreLaunchHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>and And hello again</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hercules</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/blank_layout.html.erb
<%= yield %>

app/views/layouts/pre_launch.html.erb
<!doctype html>
<html lang="pl">
<script>
    googleAnalyticsCode = '<%= ENV['GOOGLE_ANALYTICS_CODE'] %>';
  </script>

<head>
  <meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= javascript_include_tag 'application' %>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <title>evosano</title>
    <!--     Fonts     -->
    <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Lato:400,400,700|PT+Serif:400|Ubuntu:300" rel="stylesheet" type="text/css">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css" rel="stylesheet">
</head>

<body>

  <script>
      window.fbAsyncInit = function() {
          FB.init({
             appId      : '450852585053328',
             xfbml      : true,
             version    : 'v2.1'
          });
      };

     (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));

     var fb_share = function(){
       FB.ui({
         method: 'share',
         href: 'http://<%= request.host %>', //TODO różne url dla różnych środowisk
       }, function(response){});
     }
  </script>
<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">  
  <div class="container">
        <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
            <li>
            <a href="#" onclick=fb_share()>
                    <i class="fa fa-facebook-square"></i>
                    Udostępnij
                </a>
            </li>
             <li>
             <a class='tweet' title='Twój prywatny trener online. Darmowy, na zawsze.' href="http://<%= request.host %>"> 
                    <i class="fa fa-twitter"></i>
                    Tweet
                </a>
            </li>
             <li>
             <a href="mailto:info@evosano.com"
               onClick="_gaq.push(['_trackEvent', 'Contact', 'Email', 'ContactEvosano']);">
                <i class="fa fa-envelope-o"></i>
                info@evosano.com
              </a>
            </li>
       </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
<div class="main" style="background-image: url(<%=asset_path('para_z_brzuchami.jpg')%>)">

<!--    Change the image source '/images/default.jpg' with your favourite image.     -->
  
    <div class="cover black" data-color="black"></div>
     
<!--   You can change the black color for the filter with those colors: blue, green, red, orange       -->

    <div class="container">
        <h1 class="logo cursive">
            evosano
        </h1>
<!--  H1 can have 2 designs: "logo" and "logo cursive"           -->
        <div class="content">
            <h4 class="motto">Twój prywatny trener online. Darmowy, na zawsze. 
            </h4>
            <ul class="features">
                <li><i class="fa fa-check green">&nbsp;</i>Plany treningowe</li>    
                <li><i class="fa fa-check green">&nbsp;</i>Analiza postępów</li>   
              <li><i class="fa fa-check green">&nbsp;</i>Baza ćwiczeń</li>    
            </ul>
                 <%= yield %>
          </div>
    </div>
  <div class="footer">
  </div>
    <% if ENV['RAILS_ENV'] == 'development' %>
      <%= debug flash %>
    <% end %>
 </div>
 </body>

</html>

app/views/pre_launch/_errors.html.erb
<% unless flash[:errors].blank?  %>
  <div class='alert alert-danger' role='alert'>
    <% flash[:errors].each do |key, message| %>
      <%= content_tag :p, message , id: key %>
    <% end %>
  </div>
<% end %>

app/views/pre_launch/_success.html.erb
           <div class="subscribe">
              <h5 class="info-text">
              </h5>
              <div class="row">
                <div class="col-md-4 col-md-offset-4 col-sm6-6 col-sm-offset-3 ">
 <p class='alert alert-success clear' role='alert' >
<%= flash[:success] %>        
</p>
                </div>
              </div>
 

app/views/pre_launch/index.html.erb
           <div class="subscribe">
              <h5 class="info-text">
                  Chcesz wiedzieć kiedy startujemy?
              </h5>
              <div class="row">
                <div class="col-md-4 col-md-offset-4 col-sm6-6 col-sm-offset-3 ">
 
<%= render 'errors' %>
<%=form_tag pre_launch_subscribe_path, action: :pre_lauch, class: 'form-inline', role: 'form' do %>
  <div class="form-group">
    <%= email_field_tag :email, nil, class: "form-control transparent",
      placeholder:"Podaj swój email... "%>
  </div>
  <%= submit_tag 'Chcę!', class: "btn btn-danger btn-fill iwant" %>
<%end%>
                </div>
                             </div>
                              <div class='row'>
                <div class='col-md-12'>
                  <p class="info-text clear">
                  Zero spamu, tylko konkretne informacje na temat startu naszej usługi. 
                  </p>
              </div>
            </div>

 

app/views/pre_launch/subscribe.html.erb
<%= render 'success' %>